# Read the documentation: https://fosrestbundle.readthedocs.io/en/3.x/
fos_rest:
    param_fetcher_listener: true
    allowed_methods_listener: true
    routing_loader: false
    view:
        view_response_listener: 'force'
    format_listener:
        enabled: false
