
services:
  database:
    image: mysql:8.0
    container_name: brand_toplist_db
    environment:
      MYSQL_DATABASE: brand_toplist
      MYSQL_ROOT_PASSWORD: rootpass123
      MYSQL_USER: branduser
      MYSQL_PASSWORD: brandpass1234
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-prootpass123"]
      timeout: 10s
      retries: 10
      start_period: 30s
      interval: 5s
    volumes:
      - database_data:/var/lib/mysql:rw
    networks:
      - brand_toplist_network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: brand_toplist_app
    ports:
      - "8011:80"
    depends_on:
      database:
        condition: service_healthy
    environment:
      APP_ENV: dev
      APP_SECRET: a1b2c3d4e5f6g7h8i9j0k1l2m3n4o5p6
      DATABASE_URL: mysql://branduser:brandpass1234@database:3306/brand_toplist?serverVersion=8.0&charset=utf8mb4
      ADMIN_USERNAME: admin
      ADMIN_PASSWORD: admin123
      JWT_SECRET_KEY: /var/www/html/config/jwt/private.pem
      JWT_PUBLIC_KEY: /var/www/html/config/jwt/public.pem
      JWT_PASSPHRASE: ""
    volumes:
      - app_var:/var/www/html/var
    networks:
      - brand_toplist_network
    restart: unless-stopped

volumes:
  database_data:
    driver: local
  app_var:
    driver: local

networks:
  brand_toplist_network:
    driver: bridge
