# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones

    # Service Interface Bindings
    App\Service\Brand\Interface\IBrandService: '@App\Service\Brand\Implementation\BrandService'
    App\Service\Country\Interface\ICountryService: '@App\Service\Country\Implementation\CountryService'
    App\Service\TopList\Interface\ITopListService: '@App\Service\TopList\Implementation\TopListService'

    # Mapper Interface Bindings
    App\Mapper\Brand\Interface\IBrandMapper: '@App\Mapper\Brand\BrandMapper'
    App\Mapper\Country\Interface\ICountryMapper: '@App\Mapper\Country\CountryMapper'
    App\Mapper\TopList\Interface\ITopListMapper: '@App\Mapper\TopList\TopListMapper'
